import type { ActivityEntry, BoardSnapshot, ItemUpdate, WorkItem } from "./types";

export const seedItems: WorkItem[] = [
  {
    id: "demo-1",
    board_id: "demo-board-1",
    title: "Launch campaign board",
    group_name: "This week",
    owner: "Nadia",
    status: "Done",
    priority: "High",
    timeline_start: "2026-08-04",
    timeline_end: "2026-08-12",
    progress: 100,
    budget: 4200,
    description: "Coordinate launch assets, media plan, and final stakeholder approval.",
    parent_id: null,
    sort_order: 10,
  },
  {
    id: "demo-2",
    board_id: "demo-board-1",
    title: "Finalize onboarding flow",
    group_name: "This week",
    owner: "Raka",
    status: "Working on it",
    priority: "High",
    timeline_start: "2026-08-10",
    timeline_end: "2026-08-18",
    progress: 64,
    budget: 8600,
    description: "Ship the new onboarding sequence and validate activation events.",
    parent_id: null,
    sort_order: 20,
  },
  {
    id: "demo-3",
    board_id: "demo-board-1",
    title: "Collect vendor proposals",
    group_name: "This week",
    owner: "Maya",
    status: "Stuck",
    priority: "Medium",
    timeline_start: "2026-08-11",
    timeline_end: "2026-08-21",
    progress: 28,
    budget: 3200,
    description: "Compare production partners and confirm final scope.",
    parent_id: null,
    sort_order: 30,
  },
  {
    id: "demo-4",
    board_id: "demo-board-1",
    title: "Q3 product roadmap",
    group_name: "Next week",
    owner: "Dimas",
    status: "Working on it",
    priority: "Critical",
    timeline_start: "2026-08-15",
    timeline_end: "2026-08-28",
    progress: 42,
    budget: 12500,
    description: "Align product bets with growth priorities and engineering capacity.",
    parent_id: null,
    sort_order: 40,
  },
  {
    id: "demo-5",
    board_id: "demo-board-1",
    title: "Customer interview batch",
    group_name: "Next week",
    owner: "Sari",
    status: "Not started",
    priority: "Low",
    timeline_start: "2026-08-18",
    timeline_end: "2026-08-30",
    progress: 0,
    budget: 1800,
    description: "Recruit and interview twelve recently activated customers.",
    parent_id: null,
    sort_order: 50,
  },
  {
    id: "demo-6",
    board_id: "demo-board-1",
    title: "Approve final copy",
    group_name: "This week",
    owner: "Nadia",
    status: "Working on it",
    priority: "Medium",
    timeline_start: "2026-08-10",
    timeline_end: "2026-08-13",
    progress: 70,
    budget: 0,
    description: "Review paid social and landing page copy.",
    parent_id: "demo-1",
    sort_order: 11,
  },
];

export const seedUpdates: ItemUpdate[] = [
  {
    id: "update-1",
    board_id: "demo-board-1",
    item_id: "demo-2",
    author: "Nadia",
    body: "The new welcome screen is approved. Analytics review is next.",
    created_at: "2026-08-11T08:30:00.000Z",
  },
  {
    id: "update-2",
    board_id: "demo-board-1",
    item_id: "demo-3",
    author: "Maya",
    body: "Waiting for the final quote from the production partner.",
    created_at: "2026-08-11T05:15:00.000Z",
  },
];

export const seedActivity: ActivityEntry[] = [
  {
    id: "activity-1",
    board_id: "demo-board-1",
    item_id: "demo-2",
    action: "Raka changed progress to 64%",
    created_at: "2026-08-11T08:22:00.000Z",
  },
  {
    id: "activity-2",
    board_id: "demo-board-1",
    item_id: "demo-3",
    action: "Maya changed status to Stuck",
    created_at: "2026-08-11T05:10:00.000Z",
  },
];

export const seedSnapshot: BoardSnapshot = {
  items: seedItems,
  updates: seedUpdates,
  activity: seedActivity,
  attachments: [],
};
